### PR TITLE
add support for artix-7 200t and nexys video board

### PR DESCRIPTION
**Pull request by GbGp**

### CODE REVIEW

**Comment by trabucayre** [comment]
Fantastic!
Looks good for me. Just one thing, you need to update the README to add, at least, the board.

Thank!

**Comment by trabucayre** [comment]
The bitstream is missing too.

**Comment by GbGp** [comment]
Updated, the bitstream is already there (spiOverJtag/spiOverJtag_xc7a200.bit)

**Comment by trabucayre** [comment]
Thanks.
Sorry, I have not seen the bitstream this morning (lack of coffee).
Applied

**Pull request merged**
