### PR TITLE
Update boards.yml - added Alchitry Au+

### PR DESCRIPTION
**Pull request by devdc**
Tested on Alchitry Au+ and works well on macOS Monterey

### CODE REVIEW

**Comment by trabucayre** [comment]
Thanks for this PR but could you add entry near [here](https://github.com/trabucayre/openFPGALoader/blob/master/src/board.hpp#L107)? Something like
```
JTAG_BOARD("alchitry_au_plus",     "xc7a100tftg256",  "ft2232",   0, 0, CABLE_DEFAULT),
```
Since it's not the same model (size) than the `alchitry_au`, with this new entry you could use `-b alchitry_au_plus` to have everything working out of the box.
Thanks!

**Comment by devdc** [comment]
Thanks! hopefully I was able to follow your instructions :)

**Comment by trabucayre** [comment]
Applied!
Thanks!

**Comment by devdc** [comment]
Thank YOU and thanks for creating and maintaining that amazing project

**Pull request merged**
