### PR TITLE
update JTAG state machine

### PR DESCRIPTION
**Pull request by aystarik**

### CODE REVIEW

**Comment by trabucayre** [comment]
Hi,
I am agree `UPDATE_XR` have the same behaviour and next state are same, but for readability/coherency with state machine I prefer keeping both `UPDATE_XR`.

**Comment by aystarik** [comment]
OK, fair point. What do you think about pre-computing all the TMS transitions beforehand?

**Comment by trabucayre** [comment]
Why not. It's true once next state is known its possible to use an hardcoded two dimensional array to obtain the new value for TMS.

**Comment by trabucayre** [comment]
Looks good.
I have to do a closer look before applying.
Thanks!

**Pull request closed without merging**
