### PR TITLE
recognize altera cyclone V 5CEBA4 FPGA

### PR DESCRIPTION
**Pull request by emard**
With this change I can upload *.svf file,
it starts and works

### CODE REVIEW

**Comment by trabucayre** [comment]
Looks good to me, just a remark: since you add a new device/flavor the README must be updated too.

Thanks

**Comment by emard** [comment]
I'm not expert for altera product line but this device seems
identical from programming point of view, only less LUTs

**Comment by trabucayre** [comment]
When I said to update the README, it's just updating cyclone V line with this new code in the *Supported (tested) FPGA:* section

**Comment by emard** [comment]
Aha I guess I should copy exactly what is written on
FPGA chip to let other users know what is really tested

**Comment by trabucayre** [comment]
Applied thanks.
Added this cyclone V model in device supported list myself.

**Pull request merged**
