### PR TITLE
Cmake compile system proposal

### PR DESCRIPTION
**Pull request by Martoni**
This is a CMake system proposal.

### CODE REVIEW

**Comment by trabucayre** [comment]
Thanks for this work. Below some remarks
- openFPGALoader -> src
- CMakeList.txt in root directory.
- Something like:
find_package(PkgConfig REQUIRED)
pkg_check_modules(LIBFTDI REQUIRED libftdi1)
pkg_check_modules(LIBFTDIPP REQUIRED libftdipp1)
pkg_check_modules(LIBUSB REQUIRED libusb)
pkg_check_modules(LIBUDEV REQUIRED libudev)
does the same
- DOLD_FTDI_VERSION is used for a workaround with libftdi < 1.4. So a test about version is better than always 1
- your CMakeLists.txt include nothing for installation step (app in bin and bitstream in share/openFPGALoader)

**Comment by trabucayre** [comment]
Some remarks (again):
pkg_check_modules(LIBUSB REQUIRED libusb-1.0)
instead of
pkg_check_modules(LIBUSB REQUIRED libusb)

INSTALL.md use ../openFPGALoader -> ../src
missing cmake dependency in README.md
Why new INSTALL.md instead of updating README.md (with install part now out of date)?

**Comment by Martoni** [comment]
Ok fixed.

**Comment by trabucayre** [comment]
LGFM
Thanks

**Pull request merged**
