### PR TITLE
boards: Add USRP X300 and X310

### PR DESCRIPTION
**Pull request by mbr0wn**

### CODE REVIEW

**Comment by mbr0wn** [comment]
image

**Comment by trabucayre** [comment]
LGTM.
Thanks!
Have you tried to flash EEPROM? At least for xc7k325tffg900 where the spiOverJtag's bitstream is already available (for 410 it must be generated)?

**Comment by trabucayre** [comment]
Applied!
Thanks.
If you have time to test SPI flash I interested!

**Comment by trabucayre** [comment]
Ok I see. In fact I have checked X310 schematics and not seen this part. So the **NA** make sense.
Thanks.

**Pull request merged**
