### PR TITLE
Add cable jetson-nano-gpio

### PR DESCRIPTION
**Pull request by jeanbie0**
Related to the issue #259.

Tested on Jetson Nano custom board with Gowin GW1N-9C.
Added this because this FPGA need a minimal clock frequency that can be reached with libgpiod.

`-DENABLE_JETSONNANOGPIO=ON` to enable.

### CODE REVIEW

**Comment by trabucayre** [comment]
I have some questions:
- the most part of this new class is similar to `libgpiodJtagBitbang`: what do you think to inherint one of them from the other? And overriding only relevant methods?
- is this code is portable? It's seems to bypass **libgpiod** maybe it's possible to have something more generic -> possible to be used with others CPU?

I assume the **patch** file was added by error.

Thanks!

**Comment by jeanbie0** [comment]
Hello,

Yes the class is similar. But I don't thing that one of them inherent from the other. They are more sister class and inherent from class `JtagInterface `. So it seems good like this.

No code is not portable for other CPU. It depends of the internal structure of the CPU's GPIO. (Address of ports, size of ports, structure of ports,...)

Yes patch file is an error.

**Comment by trabucayre** [comment]
> Yes the class is similar. But I don't thing that one of them inherent from the other. They are more sister class and inherent from class `JtagInterface `. So it seems good like this.

I have do a diff between these two class: it's differs by CTOR, DTOR, `update_pins` and `read_tdo`. Rest of the logic remain the same. It's maybe possible to override corresponding `libgpiod`'s methods to keep logic from this one and simply add the logic required to a direct communication with CPU's controler?

> No code is not portable for other CPU. It depends of the internal structure of the CPU's GPIO. (Address of ports, size of ports, structure of ports,...)

It's make sense yes.

**Comment by jeanbie0** [comment]
So I think the most clean will be to create a mother class `GPIOBitbang` from which `libgpiodBitbang` and `jetsonNanoBitbang` inherit. So in the future it will be easy to create a class for another CPU if necessary.

**Comment by trabucayre** [comment]
Adding a super class seems the best way: it's maybe possible to use this one for ftdi bitbanging too.

**Comment by trabucayre** [comment]
Applied.
I will see howto introduce this super class and if it's possible to adapt ftdijtagbitbang to this new structure.
Thanks!

**Pull request merged**
