### PR TITLE
Add FTDI channel selection command line argument.

### PR DESCRIPTION
**Pull request by ronyrus**
Some boards have FTDI JTAG connected to the FPGA on different channel.
It's helpful to be able to provide the channel on command line.

### CODE REVIEW

**Comment by trabucayre** [comment]
True. It's a great idea.
I've just two comment:

- part added in the main function and the function `ftdi_update_channel` are primarly sanity check, I prefer this part in part_opt (as done for [pins](https://github.com/trabucayre/openFPGALoader/blob/master/src/main.cpp#L320)). The simpliest way is to check if ID are correct and update ftdi_channel with the ID of the channel. So, in the `main` it's just mandatory to check if this option is != -1 and if it's an ftdi cable before updating cable.config.interface (without new function addition).
- the README must be updated to reflect this new option

Thanks

**Comment by ronyrus** [comment]
done
was looking at the readme and it seems that "-d" is no longer with us...

**Comment by trabucayre** [comment]
Look Good.
Applied thanks

**Comment by trabucayre** [comment]
-d or --device is used if udev support is enable.

**Pull request merged**
