### PR TITLE
Add CH347T(mode #3) JTAG cable

### PR DESCRIPTION
**Pull request by aystarik**
checked with gowin fpga

### CODE REVIEW

**Comment by trabucayre** [comment]
I have tried with a spartan7 and I'm able to load a bitstream but I observe

```
openFPGALoader -c ch347_jtag /tmp/blink.bit 
JTAG TCK frequency set to 8 MHz

Open file DONE
Parse file DONE
load program
writeTDI: invalid read data: 
writeTDI: invalid read data: 
writeTDI: invalid read data: 
writeTDI: invalid read data: 
Flash SRAM: [==================================================] 100.00%
Done
```

After one first try I'm no more able to detect device and I must to power cycle the ch347 (it's one with bcDevice 2.41).

**Comment by aystarik** [comment]
Can you do the log with "--verbose-level 2" ?

**Comment by trabucayre** [comment]
Both loading and fail are loading are attached here:
[ofl_ch347.txt](https://github.com/trabucayre/openFPGALoader/files/11474750/ofl_ch347.txt)
[ofl_ch347_fail.txt](https://github.com/trabucayre/openFPGALoader/files/11474752/ofl_ch347_fail.txt)

**Comment by trabucayre** [comment]
With the last commit, openFPGALoader seems blocked.
I have added some `printf` it not an infinite loop, I have to check a bit more: maybe a command was not correctly sent and openFPGALoader wait for a status bit but FPGA hasn't received the request.

**Comment by trabucayre** [comment]
Hi,
After a bit of delay I have restarted to test this support.
I have fixed some few thing (mainly around clk configuration) and successfully tested with an intel cycloneV FPGA.
Patch is now manually [applied](0fc8ba10a8e73439e738562da86fcee01b157e8e)

Thanks

**Pull request closed without merging**
