### PR TITLE
support for CH347T JTAG mode (3)

### PR DESCRIPTION
**Pull request by aystarik**
checked with LA only

### CODE REVIEW

**Comment by trabucayre** [comment]
Have you link to a compatbile board and firmware to use ?
Also doc must be updated.

**Comment by aystarik** [comment]
https://github.com/wuxx/USB-HS-Bridge -- here is the board I work with. chip does not require any additional firmware.

**Comment by aystarik** [comment]
checked with real JTAG, it breaks at the usleep() points.

**Comment by trabucayre** [comment]
I have ordered one board but with more or less one month for delivery... I will try to see how to fix/help with that.

**Comment by aystarik** [comment]
great!

**Pull request closed without merging**
