### PR TITLE
Add WebAssembly support

### PR DESCRIPTION
**Pull request by whitequark**
I got openFPGALoader to work with WebUSB with this patch (tested on OrangeCrab r0.2).

### CODE REVIEW

**Comment by trabucayre** [comment]
Applied! Thank @whitequark

**Comment by whitequark** [comment]
Thanks! Do you think I should be shipping releases of openFPGALoader as a part of [YoWASP toolchain](https://marketplace.visualstudio.com/items?itemName=yowasp.toolchain) or if I should ship the master branch?

**Comment by trabucayre** [comment]
Good question.  I think master branch is better:
1. Current master branch has improvements for nexus devices and support for gowin GW5A so It seems  better in a first time to use it.
2.  more generically I create a new release more or less each 6 month. It a lood delay when improvement are applied.
3. your fixes are on master branch.

But in other hand I try to fix all known issues and fix regression before tagging a commit (this why I not iregular for releases).

**Comment by whitequark** [comment]
It sounds like adding automation that ships the master branch nightly is the way to go here. (Obviously I can change this later, I have scripts tailored for different workflows.)

**Comment by trabucayre** [comment]
If it's possible without to many works it seems good yeah. 
Or I can create a tag by incrementing minor number if you prefer.

**Comment by whitequark** [comment]
Already set up in fact! https://www.npmjs.com/package/@yowasp/openfpgaloader?activeTab=versions

**Comment by trabucayre** [comment]
Great! Thanks a lot for your work!

**Pull request merged**
