### PR TITLE
Tell USB bus and address when ftdi open fails.

### PR DESCRIPTION
**Pull request by inkdot7**
Idea is to give user some more hints when open failed.

### CODE REVIEW

**Comment by trabucayre** [comment]
It's a good idea, but this piece of code is used when `_bus` and `_addr` are provided by user, but also when both aren't. So, in latter case this may introduce difficulties for user.
It's maybe required here to duplicate message to adapt content.

**Comment by inkdot7** [comment]
I think I also were looking for that info when `_bus` and `_addr` had been set automatically.  The extra info might make it easier to figure out what went wrong also in the automatic case.

**Comment by inkdot7** [comment]
Though, my original problem then turned out to be #354, so when giving them explicitly.

How about changing the message from ` (USB bus %d addr %d)` to ` (at USB bus %d addr %d)`?  That would more indicate what failed to open.

**Comment by trabucayre** [comment]
`_bus` and `_addr` have a value != 0 only when:
- user provides both informations `--busdev-num`
- user select a device `--device /dev/ttyUSBx`

So I think it's required to replace the common message by two according to the presence/absence of these informations.

**Comment by inkdot7** [comment]
Oh, now I see.  Yes, with just 0 and 0, it would be more confusing.

I tried to make some formatting that mimicked how the device is opened and noticed that when nothing is specified on the command line, most values (vid, pid, serial, index) are all 0.  So printing them instead would not be helpful.

Though what I made now looks rather clumsy.

Perhaps it is better if, at higher verbosity level, it tells what it tries to open and how.

**Comment by trabucayre** [comment]
Applied thanks @inkdot7

**Pull request merged**
