### PR TITLE
Support for the Microchip SST25VF040B flash

### PR DESCRIPTION
**Pull request by rstephan**
Programming is slow, only one byte at a time :-(

See https://github.com/trabucayre/openFPGALoader/pull/203

### CODE REVIEW

**Comment by trabucayre** [comment]
LGTM.
Yes AAI mode seems mandatory to reduce write time!
Just two thing: 
- there is not TB so this is a use case to integrate
- BP bits can't be updated if `BPL` (status register bit 7) is high -> again a use case to integrate into `enable_protection` and `disable_protection`

It's not to ask you to add these feature, I can, of course, add those by myself once this PR is applied.

Thanks

**Comment by rstephan** [comment]
At least the TB settings are removed form my side.
I am fine, if you can implement `enable_protection`/`disable_protection` yourself.
You know better how to find the right place in your code. ;-)
Thanks!

**Comment by trabucayre** [comment]
Could you just remove test about bp lines 314-317.
For bypassing TB, I will do that by myself, it's okay.
Thanks

**Comment by trabucayre** [comment]
Applied thanks!
I have added logic to handle flash without TB bit.

**Pull request merged**
