### PR TITLE
Add support  for Terasic DE1-SoC board

### PR DESCRIPTION
**Pull request by tarikgraba**
This pull request should be attributed to @sedwards-lab (see issue #159)

### CODE REVIEW

**Comment by trabucayre** [comment]
LGTM but please update [FPGA list](https://github.com/trabucayre/openFPGALoader/blob/master/doc/FPGAs.yml#L62) and [board list](https://github.com/trabucayre/openFPGALoader/blob/master/doc/boards.yml)

I fact I don't know how to attribute a PR to a different one.

Thanks!

**Comment by tarikgraba** [comment]
@trabucayre what are the fields Memory/Flash for in FPGA.yml?

**Comment by trabucayre** [comment]
**memory** is if openFPGALoader can load bitstream into SRAM (ie volatile storage)
**flash** is if the bitstream may be wrtten into internal or external flash (ie non volatile storage)

For example **Zynq** has *NA* for **flash**, because the flash is accessible only by PS and **xfm** (a PROM device) has *NA* for **memory** because it's a JTAG flash.

For cycloneV SoC, theoritically it's possible to write bitstream into connected flash, but unfortunately I'm currently unable to do that.

**Comment by trabucayre** [comment]
Thanks!
But the commit will be with your address instead of @sedwards-lab one

**Comment by tarikgraba** [comment]
I have marked the flash as not tested and changed one of the commits

**Comment by sedwards-lab** [comment]
No worries that the commit is under a different name. I'm just glad that support was added

**Comment by trabucayre** [comment]
Applied to master!
Thanks!

**Pull request merged**
