### PR TITLE
Added Lone Dynamics Schoko and Konfekt SBCs

### PR DESCRIPTION
**Pull request by wdevore**
Added two new entries from **Machdyne**'s SBCs.

### CODE REVIEW

**Comment by trabucayre** [comment]
LGTM. just few remarks:

- could you sort by alphabetic order (I know not all boards are corretly ordered)
- for them with a jtag access (and since there is no onboard adapter) cable name must be left blank. User must provides explicity this information.

Thanks!

**Comment by wdevore** [comment]
Remove cable name and alpha sorted

**Comment by trabucayre** [comment]
Great! Thanks to have reordered all boards!
But unfortunately there is a conflict between your branch and master branch.

**Comment by wdevore** [comment]
Well, I tried merging between forks, but I really am not that skilled at it. I done plenty of merging with my own repos. Not sure how to "fix" this.

**Comment by wdevore** [comment]
I backed out some of the sorting to fix merge conflict.

**Comment by trabucayre** [comment]
I have [applied](https://github.com/trabucayre/openFPGALoader/commit/9a09e427e3700316453cf23a25f494e980b1de9b) this commit manually.
Thanks again!

**Comment by trabucayre** [comment]
One way to fix this situation where a conflict appears is:
- first you save your commit (or at least files modified)
- using `git reset --hard CommitHashBeforeYourFirstCommit`

Here you here at the point before your first commit and now you have to rebase
- `git remote add upstream gitUrl`
- `git fetch upstream`
- `git rebase upstream/master`

Now your branch is similar to official repo: next apply again your modifications, checking everything and new `git add xxx`, `git commit -m "xxx"` and `git push xxx`

There is off course some usefull commands (`git cherry-pick`, `git am`, etc.) but this solution may be more simple in a first time.

**Pull request closed without merging**
