### PR TITLE
limit the progressBar update rate to 5 per second. This speeds up loa…

### PR DESCRIPTION
**Pull request by phdussud**
Hello! 
I would like to submit this small change to the progress bar. It limit its update rate to 5 updates a second. This does speed up the loading of small bin files because the terminal takes time to redisplay the bar. 
Thanks a lot. 
Patrick.

### CODE REVIEW

**Comment by trabucayre** [comment]
Good idea!
Only one small remark: `last_time` must be a class member, with an initialization at constructor time, currently the first time `display` is called `last_time` has an unknown value.

Thanks

**Comment by phdussud** [comment]
I agree! I will make the change. I just want to point out that right now the static has a well-defined value of 0 when the program starts. It is per C and C++ standard.
Thanks!
Patrick
________________________________

**Comment by phdussud** [comment]
Done! 
Thanks again, 
Patrick

**Comment by trabucayre** [comment]
Sorry for delay.
LGTM
applied Thanks

**Comment by phdussud** [comment]
Thank you very much. 
I have been working on adding a new cable, the breakout board for the Cypress FX2LP. A board costs about $8 at amazon 
https://www.amazon.com/EZ-USB-FX2LP-CY7C68013A-Analyzer-Source/dp/B081DH4TN3
It is about 2x slower than a good FT232H cable. These boards are popular as logic analyzers, as they are supported by sigrok.org
I have done the port using the excellent library libfpgalink : https://github.com/makestuff/libfpgalink
The downside of this port is that it adds external dependencies, namely the above git repo. I am not sure it is justified for a normal release of openFPGAloader that is very tight and relies only on distro supported dependencies. 
I see 3 ways around this:
- Drop this idea. 
- Make it a conditional compilation feature and leave it off by default. 
- Try to make libfpgalink delay loaded, which seems possible even under Linux using this component: https://github.com/yugr/Implib.so
The port itself is simple because your jtag abstraction matches fairly well with the libfpgalink API. 
Please let me know your thoughts on this. 
Patrick

**Comment by trabucayre** [comment]
I'm open to all new cable (maybe I need to order one of this), and not oppossed to add dependencies to external libraries when it's possible instead of reimplementing everything from scratch (it's depends more or less to the complexity).
The idea of using an option to enable this cable seems good, these allows to have something simple for most people but allowed to use some features when it's needed.

**Comment by phdussud** [comment]
Based on your comments, I went ahead and modified the cmake file to include FX2 support only when it can find libfpgalink on the path. This is analogous to the treatment of libudev.

**Comment by trabucayre** [comment]
Maybe an `option` is required to let user decide if he want to add support to this cable or not. Of course, test about library is mandatory.
I'm not usually happy when a build system decide for me what to build according to libraries present in my OS.
I'm interested to see your modifications.

**Comment by phdussud** [comment]
Sounds good. Do you prefer to have a look on my forked repo on github or for me to submit a PR?
Thanks,
Patrick
________________________________

**Comment by trabucayre** [comment]
The best solution is to update your fork and send a PR when you consider you are satisfied by your implementation.

**Pull request merged**
