### PR TITLE
part: add support for Anlogic ELF2 EF2M45

### PR DESCRIPTION
**Pull request by Icenowy**
Anlogic EF2M45 is a FPGA with a co-packaged 4Mbit SPI Flash, and the
JTAG interface is the same with EG4S20.

Add support for it by adding it to the part database.

SPI Flash programming and SRAM programming are both tested.

Signed-off-by: Icenowy Zheng <icenowy@aosc.io>

### CODE REVIEW

**Comment by trabucayre** [comment]
LGTM
But could you update [fpga list](https://github.com/trabucayre/openFPGALoader/blob/master/doc/compatibility/fpga.rst) too?
Are there a board based on this device ?
Thanks

**Comment by Icenowy** [comment]
No board is commercially available now, as I know. (BTW EF2L45LG144B has MCU enabled too, so it should be in EF2M45 family.  This may have some boards available)

I designed one with a few samples from Anlogic, and open-sourced it (current version on my GitHub is a broken one from 2019, I reworked it some days ago, waiting for JLCPCB to deliver the new PCB).

**Comment by Icenowy** [comment]
BTW for the FPGA list, EG4S20 should be Flash OK, not AS (because it's still flashing via JTAG, although a JTAG-SPI channel is built into Anlogic FPGA hardware, so it's why EF2M45 internal flash can be flashed)

**Comment by trabucayre** [comment]
It's true: flash status must be OK instead of AS -> fixed.
Feel free to add your board if everything is available to reproduce / have access. The honeycomb is referenced but there is no store to bough one.

**Comment by trabucayre** [comment]
Applied to master!
Thanks

**Pull request merged**
