### PR TITLE
support Kintex XC7K420T

### PR DESCRIPTION
**Pull request by hansfbaier**
This fixed issue #219 for me.
Was able to upload a working blinky.

### CODE REVIEW

**Comment by trabucayre** [comment]
LGTM.
Applied Thanks!
Fee free to create spiOverJtag bitstream to write bitstream to SPI flash :)

**Comment by hansfbaier** [comment]
If you tell me where to look for resources I might give it a try

**Comment by trabucayre** [comment]
Everything about that is in [spiOverJtag](https://github.com/trabucayre/openFPGALoader/tree/master/spiOverJtag) subdirectory.
See:
- [this commit](https://github.com/trabucayre/openFPGALoader/commit/dd85b5a579751928267ebefe5f7b97c3df6781ad) to add new FPGA variant
- [this](https://github.com/trabucayre/openFPGALoader/commit/eb4ac2536ad576601234a02bc0ecfc1337e6c349) if there is no xdc file for your device + package.

I'm agree a documentation must be written, but I have postponed this task until build.py will be simplified.

**Comment by hansfbaier** [comment]
Ah I see, thanks, that should do.
I will use ISE though, because Vivado is paid for Kintex larger than 325T and larger.

**Pull request merged**
