### PR TITLE
add support for colorlight-i9+ board

### PR DESCRIPTION
**Pull request by infphyny**
Pull request for adding colorlight i9+ via an ftdi 2232.  I didn't change that much in Makefile and board.hpp. Maybe I did a mistake somewhere. Let me know and I will change the pull request.

### CODE REVIEW

**Comment by trabucayre** [comment]
Seems your branch is out of date, with some conflict.
colorlight i9+ has no onboard jtag interface no?

**Comment by infphyny** [comment]
Ok forgot to update the cloned repository on my side. colorlight-i9+ carrier board have no onboard jtag interface. Can only upload via ch347t that need an out of tree openocd. The module have accessible jtag pins.

**Comment by trabucayre** [comment]
Hi,
Could you rebase your fork. It's to reduce history to only spiOverJtag update + colorlight addition.
Usually when a board as no onboard jtag interface cable name is left empty: user has to provides explicitly this information.

If you prefer I can fix and apply the patch manually. As you want

Thanks!

**Comment by infphyny** [comment]
You can apply the patch manually.  I agree with you, better leave cable name empty. 
Thanks.

**Comment by trabucayre** [comment]
Applied! Thanks @infphyny

**Pull request closed without merging**
