### PR TITLE
Add qmtechCycloneV_5cefa5f23 board and spiOverJtag/spiOverJtag_5cefa5…

### PR DESCRIPTION
**Pull request by infphyny**
qmtechCycloneV_5cefa5f23 board added and bitstream generated with quartus 20.1 .

### CODE REVIEW

**Comment by infphyny** [comment]
I will add the board documentation in doc/boards.yml in another pull request.

**Comment by trabucayre** [comment]
If you see others parts: the naming convention is `5ce` + size + packagepin

According to CV-51001:

- first `F` (or `B`) is about PCIe and hard memory controler
- `Ax` is the die size (and `A` is always present)
- last `F` is the package type

This why naming is reduce to address the device (`5CE`, `5CSE`, ...), die size (without `A`), and package size.

For doc it's make sense to have both support and documentation in one PR (this reduce the number of merge commits for one board)

**Comment by infphyny** [comment]
Changed 5cefa5f23 to 5ce523. Added documentation for board and fpga. If there are other thing that need to be changed let me know.

Merci.

**Comment by trabucayre** [comment]
LGTM.
Applied thanks!

**Pull request merged**
