### PR TITLE
Adding TangNano (gowin)

### PR DESCRIPTION
**Pull request by Martoni**
For the moment, tangnano doesn't works:
```
$ openFPGALoader -v -m -b tangnano ./lcd_pjt/impl/pnr/lcd_pjt.fs
erreur de write
erreur de write
erreur de write
erreur de write
erreur de write
erreur de write
erreur de write
found 5 devices
Error: currently only one device is supported
```

### CODE REVIEW

**Comment by Martoni** [comment]
According to [Kongou Hikari](http://www.fabienm.eu/flf/longan-nano-deballage/#comments) The second tty (ttyUSB1 on my computer) is a MPSSE endpoint used to program the FPGA. If it can help .

**Comment by trabucayre** [comment]
Hi,
Can you try to change in lines 123 and 125 value '1' by '2':
```
if (args.device == "-")
        jtag = new FtdiJtag(cable, 2, 6000000, false);
    else
        jtag = new FtdiJtag(cable, args.device, 2, 6000000, false);
```
These values corresponds to the FT2232's (or clone) interface:
- 1 -> interfaceA (first /dev/ttyUSBx)
- 2 -> interfaceB (second /dev/ttyUSBx)

If it's work I must founds a way to select correct interface.
I'm waiting for tangNano board I've ordererd.

**Comment by trabucayre** [comment]
About the patch GW1N-1 and GW1N-9 are both GW1N family in opposition to GW2A.
Could you fix this

**Comment by Martoni** [comment]
With this patch :
```
diff --git a/main.cpp b/main.cpp
index e7ddc1e..d9e1efa 100644
--- a/main.cpp
+++ b/main.cpp
@@ -120,9 +120,9 @@ int main(int argc, char **argv)
        /* jtag base */
        FtdiJtag *jtag;
        if (args.device == "-")
-               jtag = new FtdiJtag(cable, 1, 6000000, false);
+               jtag = new FtdiJtag(cable, 2, 6000000, false);
        else
-               jtag = new FtdiJtag(cable, args.device, 1, 6000000, false);
+               jtag = new FtdiJtag(cable, args.device, 2, 6000000, false);
 
        /* chain detection */
        vector<int> listDev;
```

I've got this error:
```
penFPGALoader -v -m -b tangnano ./lcd_pjt/impl/pnr/lcd_pjt.fs
Error: write for frequency
erreur de write
erreur de write
```
And the program is blocked.

**Comment by trabucayre** [comment]
Ok. Thanks for the test.
Problem with this board is the device between usb connector and FPGA. It's not an ft2232 but a microntroler cloning this converter. So maybe I'm too strict (or libftdi) or maybe this device has issue with the implementation.
I need to wait to receipt my tangNano to search for a workaround.
Your PR is okay for me, but I prefer waiting for a workaround, to verify if openFPGALoader is working with this version, before applying this.

**Comment by trabucayre** [comment]
Thank

**Pull request merged**
